### PR TITLE
Fix #19, Uncaught TypeError: domNode.replaceData is not a function

### LINKED ISSUE #19: Uncaught TypeError: domNode.replaceData is not a function
## Issue

Using nested tagger result in either an exception or the wrong domnode being modified

Patch indices are collapsed for nested tagger in [diffHelp](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L536)  but not in [addDomNodesHelp](https://github.com/elm-lang/virtual-dom/blob/master/src/Native/VirtualDom.js#L813)

## Reproduction

```elm
import Html exposing (div, text, button)
import Html.App exposing (beginnerProgram, map)
import Html.Events exposing (onClick)


main =
    beginnerProgram 
        { model = Page1
        , view = view
        , update = update
        }
        
        
type Page 
    = Page1
    | Page2
        
        
view model =
    case model of
        Page1 ->
            div []
                [ div []
                      [ button [ onClick Click ] [ text "change page" ] ]
                , text "page 1"
                ]
            |> map (always (always IntermediateMsg))
            |> map (always (ChangePage Page2))
        Page2 ->
            div []
                [ button [ onClick Click ] [ text "change page" ]
                , text "page 2"
                ]
            |> map (always (always IntermediateMsg))
            |> map (always (ChangePage Page1))
        

type Msg 
    = ChangePage Page
    
type IntermediateMsg
    = IntermediateMsg
    
type SubMsg
    = Click
    
update msg model =
    case msg of
        ChangePage page ->
            page
```

### PR DESCRIPTION
**Pull request by Iznaak**

### CODE REVIEW

**Comment by domenkozar** [comment]
@Iznaak do you have an elm file to reproduce this error?

**Comment by jvoigtlaender** [comment]
@domenkozar, you mean like the elm file given in #19, the issue this pull request is stating to fix? :smile:

**Comment by evancz** [comment]
@domenkozar, I agree with your question. @jvoigtlaender, a high quality issue or PR is self contained. I know you are fine clicking through arbitrarily many links, but the more exploration you have to do to understand a PR or issue, the harder it is and the longer it takes.

I am going to delete all these comments now. Want to keep things focused. Don't want to talk about this stuff any more.

**Comment by evancz** [comment]
Cool, thank you! I went through the logic today and everything makes sense to me.

**Comment by niksilver** [comment]
Excellent, thanks, @Iznaak - this also fixes elm-lang/core#615 as @evancz predicted.

**Pull request merged**
